Algoritmo "ProgramaAbastecimento"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Fernanda Pereira

Var
  litros, reais: real


Inicio
 //Entrada
 escreval ("O valor da gasolina esta R$4,30")
 escreval ("Quanto reais deseja abasteser:R$ ")
 leia (reais)

  //Processamento
   litros:= reais / 4.30
  
  //Saida
  escreva ("O total de litros comprados foi de:", litros, "L")



Fimalgoritmo
